### ISSUE TITLE
Problems when no internet connection

### ISSUE THREAD

**Issue by erakli** [cjnaz/RCloneSync#17]
After sync without internet RCloneSync need --FirstSync again. I added it to crontab for calling script every 30 minutes. When I work on my notebook with no internet connection, I then get messages in log like 

```
2018-05-10 09:30:02,676/:  ***** BiDirectional Sync for Cloud Services using RClone *****
2018-05-10 09:30:03,208/:  Synching Remote path  <yandex-disk:>  with Local path  </home/egor-home/Clouds/Yandex.Disk/>
2018-05-10 09:30:03,249/:  >>>>> Generating Local and Remote lists
2018/05/10 09:30:04 ERROR : : error listing: Get https://cloud-api.yandex.com/v1/disk/resources?limit=1000&offset=0&path=disk%3A%2F: EOF
2018/05/10 09:30:04 Failed to lsl: Get https://cloud-api.yandex.com/v1/disk/resources?limit=1000&offset=0&path=disk%3A%2F: EOF
2018-05-10 09:30:04,123/:    WARNING  rclone lsl try 0 failed.            - yandex-disk:
...
2018-05-10 09:30:04,206/:    ERROR    rclone lsl failed.  Specified path invalid?  (Line 170) - yandex-disk:
2018-05-10 09:30:04,206/:  ***** Critical Error Abort - Must run --FirstSync to recover.  See README.md *****
2018-05-10 09:30:04,252/:  >>>>> All done.
```

And then, obviously get
```
2018-05-10 10:30:01,143/:  ***** BiDirectional Sync for Cloud Services using RClone *****
2018-05-10 10:30:01,159/:  Synching Remote path  <yandex-disk:>  with Local path  </home/egor-home/Clouds/Yandex.Disk/>
2018-05-10 10:30:01,159/:  ***** Cannot find prior local or remote lsl files.
2018-05-10 10:30:01,159/:  ***** Critical Error Abort - Must run --FirstSync to recover.  See README.md *****
2018-05-10 10:30:01,159/:  >>>>> All done.
```

It would be convenient to preserve such situations.

**Comment by cjnaz** [comment]
It looks like you  are not using the `--CheckAccess` feature.  If enabled (need to place 1 or more RCLONE_TEST files in your directory tree) then if there is no access to the local or remote system then RCloneSync aborts with RTN_ABORT which leaves the sync history files intact for the next retry.  With `--CheckAccess` not enabled the code proceeds to get the current local and remote LSLs, and if these fail then it's a RTN_CRITICAL, which requires a `--FirstSync` to recover.  The assumption is that access has been confirmed in the checkAccess stage.  See the README.md for more info.  Early on, I got clobbered by access failures resulting in deleting all files on the other side and then on the next successful sync it deleted all the file on the first system, so there are several safety checks in place.

**Comment by erakli** [comment]
Yeah, I remember, I tried this command firstly, but I got some errors. Then I tried without it and it goes fine except on run without internet.

So, I gave a try to this command again now and got 

```
$ /home/egor-home/git/RCloneSync/RCloneSync.py yandex-disk: ~/Clouds/Yandex.Disk --ExcludeListFile ~/Clouds/yandex_exclude --Verbose --CheckAccess

2018-05-12 22:35:36,455/:  ***** BiDirectional Sync for Cloud Services using RClone *****
2018-05-12 22:35:36,592/:  Synching Remote path  <yandex-disk:>  with Local path  </home/egor-home/Clouds/Yandex.Disk/>
2018-05-12 22:35:36,592/:  >>>>> Checking rclone Local and Remote filesystems access health
2018-05-12 22:36:12,034/:    ERROR    Failed access health test:  <RCLONE_TEST> local count 0, remote count 0 - 
2018-05-12 22:36:12,035/:  ***** Critical Error Abort - Must run --FirstSync to recover.  See README.md *****
2018-05-12 22:36:12,050/:  >>>>> All done.
```
Before this everything was ok. 

Great, I thought, and called RCloneSync with --FirstSync...

```
$ /home/egor-home/git/RCloneSync/RCloneSync.py yandex-disk: ~/Clouds/Yandex.Disk --ExcludeListFile ~/Clouds/yandex_exclude --Verbose --FirstSync
2018-05-12 22:36:31,993/:  ***** BiDirectional Sync for Cloud Services using RClone *****
2018-05-12 22:36:32,036/:  Synching Remote path  <yandex-disk:>  with Local path  </home/egor-home/Clouds/Yandex.Disk/>
2018-05-12 22:36:32,036/:  >>>>> Generating --FirstSync Local and Remote lists
2018-05-12 22:36:52,694/:    REMOTE     Copying to local                  - /home/egor-home/Clouds/Yandex.Disk/МАИ/WING IN GROUND EFFECT VEHICLE: MODELLING AND CONTROL.pdf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd31b4e]

goroutine 58 [running]:
github.com/ncw/rclone/yandex.(*Fs).List(0xc4201ab720, 0x0, 0x0, 0x75d849, 0xc42011c400, 0x0, 0x0, 0x0)
	/home/ncw/go/src/github.com/ncw/rclone/yandex/yandex.go:228 +0x4de
github.com/ncw/rclone/fs.ListDirSorted(0x158c9e0, 0xc4201ab720, 0x429800, 0x0, 0x0, 0x0, 0x75d963, 0xc420568730, 0xc420568738, 0x7ffffffe)
	/home/ncw/go/src/github.com/ncw/rclone/fs/operations.go:629 +0x63
github.com/ncw/rclone/fs.(*march).makeListDir.func1(0x0, 0x0, 0xc4200121e0, 0x0, 0xc420074120, 0x75d76d, 0x1)
	/home/ncw/go/src/github.com/ncw/rclone/fs/march.go:70 +0x53
github.com/ncw/rclone/fs.(*march).processJob.func1(0xc4200121e0, 0xc4200462a0, 0xc4202ec100, 0xc42011c400, 0x0, 0x0, 0x0, 0x0, 0x7ffffffe, 0x7ffffffe, ...)
	/home/ncw/go/src/github.com/ncw/rclone/fs/march.go:330 +0x6f
created by github.com/ncw/rclone/fs.(*march).processJob
	/home/ncw/go/src/github.com/ncw/rclone/fs/march.go:328 +0xede
2018-05-12 22:36:52,981/:    WARNING  rclone copyto try 0 failed.         - yandex-disk:МАИ/WING IN GROUND EFFECT VEHICLE: MODELLING AND CONTROL.pdf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd31b4e]

goroutine 70 [running]:
github.com/ncw/rclone/yandex.(*Fs).List(0xc4202ac0a0, 0x0, 0x0, 0x75d849, 0xc4202d0300, 0x0, 0x0, 0x0)
	/home/ncw/go/src/github.com/ncw/rclone/yandex/yandex.go:228 +0x4de
github.com/ncw/rclone/fs.ListDirSorted(0x158c9e0, 0xc4202ac0a0, 0x429800, 0x0, 0x0, 0x0, 0x75d963, 0xc420451730, 0xc420451738, 0x7ffffffe)
	/home/ncw/go/src/github.com/ncw/rclone/fs/operations.go:629 +0x63
github.com/ncw/rclone/fs.(*march).makeListDir.func1(0x0, 0x0, 0xc420012620, 0x0, 0xc420454000, 0x75d76d, 0x1)
	/home/ncw/go/src/github.com/ncw/rclone/fs/march.go:70 +0x53
github.com/ncw/rclone/fs.(*march).processJob.func1(0xc420012620, 0xc42021c280, 0xc4203ac0b0, 0xc4202d0300, 0x0, 0x0, 0x0, 0x0, 0x7ffffffe, 0x7ffffffe, ...)
	/home/ncw/go/src/github.com/ncw/rclone/fs/march.go:330 +0x6f
created by github.com/ncw/rclone/fs.(*march).processJob
	/home/ncw/go/src/github.com/ncw/rclone/fs/march.go:328 +0xede
2018-05-12 22:36:53,465/:    WARNING  rclone copyto try 1 failed.         - yandex-disk:МАИ/WING IN GROUND EFFECT VEHICLE: MODELLING AND CONTROL.pdf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd31b4e]

goroutine 70 [running]:
github.com/ncw/rclone/yandex.(*Fs).List(0xc420189770, 0x0, 0x0, 0x75d849, 0xc420194880, 0x0, 0x0, 0x0)
	/home/ncw/go/src/github.com/ncw/rclone/yandex/yandex.go:228 +0x4de
github.com/ncw/rclone/fs.ListDirSorted(0x158c9e0, 0xc420189770, 0x429800, 0x0, 0x0, 0x0, 0x75d963, 0xc420108f30, 0xc420108f38, 0x7ffffffe)
	/home/ncw/go/src/github.com/ncw/rclone/fs/operations.go:629 +0x63
github.com/ncw/rclone/fs.(*march).makeListDir.func1(0x0, 0x0, 0xc42030e140, 0x0, 0xc4201ce600, 0x75d76d, 0x1)
	/home/ncw/go/src/github.com/ncw/rclone/fs/march.go:70 +0x53
github.com/ncw/rclone/fs.(*march).processJob.func1(0xc42030e140, 0xc4204e6240, 0xc42030a060, 0xc420194880, 0x0, 0x0, 0x0, 0x0, 0x7ffffffe, 0x7ffffffe, ...)
	/home/ncw/go/src/github.com/ncw/rclone/fs/march.go:330 +0x6f
created by github.com/ncw/rclone/fs.(*march).processJob
	/home/ncw/go/src/github.com/ncw/rclone/fs/march.go:328 +0xede
2018-05-12 22:36:53,834/:    WARNING  rclone copyto try 2 failed.         - yandex-disk:МАИ/WING IN GROUND EFFECT VEHICLE: MODELLING AND CONTROL.pdf
2018-05-12 22:36:53,834/:    ERROR    rclone copyto failed.  (Line 122)   - yandex-disk:МАИ/WING IN GROUND EFFECT VEHICLE: MODELLING AND CONTROL.pdf
2018-05-12 22:36:53,854/:  ***** Critical Error Abort - Must run --FirstSync to recover.  See README.md *****
2018-05-12 22:36:53,882/:  >>>>> All done.
```

Interesting. I checked this file on cloud and it seems fine. Also, it not synced at all. It seems rclone error, 
but see no reason why it happened.

**Comment by erakli** [comment]
Ok, it's me again. 

After I synced over `rclone`, everything works fine. I tried to remove this file (`WING IN GROUND EFFECT VEHICLE: MODELLING AND CONTROL.pdf`) from `local`, it synced, ok. 

Then I added it again to `remote`. Sync went fine.

And then, I renamed it on `remote` from `WING IN GROUND EFFECT VEHICLE_ MODELLING AND CONTROL.pdf` (with underscore) to `WING IN GROUND EFFECT VEHICLE MODELLING AND CONTROL.pdf` (without) and got next output:
```
$ /home/egor-home/git/RCloneSync/RCloneSync.py yandex-disk: ~/Clouds/Yandex.Disk --ExcludeListFile ~/Clouds/yandex_exclude --Verbose --rcVerbose --CheckAccess
2018-05-12 23:40:50,513/:  ***** BiDirectional Sync for Cloud Services using RClone *****
2018-05-12 23:40:50,526/:  Synching Remote path  <yandex-disk:>  with Local path  </home/egor-home/Clouds/Yandex.Disk/>
2018-05-12 23:40:50,526/:  >>>>> Checking rclone Local and Remote filesystems access health
2018-05-12 23:41:24,134/:  >>>>> Generating Local and Remote lists
2018-05-12 23:41:43,452/:    LOCAL    Checking for Diffs                  - /home/egor-home/Clouds/Yandex.Disk/
2018-05-12 23:41:43,465/:    REMOTE   Checking for Diffs                  - yandex-disk:
2018-05-12 23:41:43,467/:    REMOTE     File was deleted                  - МАИ/WING IN GROUND EFFECT VEHICLE_ MODELLING AND CONTROL.pdf
2018-05-12 23:41:43,476/:    REMOTE     File is new                       - МАИ/WING IN GROUND EFFECT VEHICLE MODELLING AND CONTROL.pdf
2018-05-12 23:41:43,478/:       2 file change(s) on REMOTE:    1 new,    0 newer,    0 older,    1 deleted
2018-05-12 23:41:43,478/:  >>>>> Applying changes on Remote to Local
2018-05-12 23:41:43,478/:    REMOTE     Copying to local                  - /home/egor-home/Clouds/Yandex.Disk/МАИ/WING IN GROUND EFFECT VEHICLE MODELLING AND CONTROL.pdf
2018/05/12 23:41:43 INFO  : Local file system at /home/egor-home/Clouds/Yandex.Disk/МАИ: Modify window is 1ns
2018/05/12 23:41:46 INFO  : WING IN GROUND EFFECT VEHICLE MODELLING AND CONTROL.pdf: Copied (new)
2018/05/12 23:41:46 INFO  : 
Transferred:   6.182 MBytes (2.151 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:        2.8s

2018-05-12 23:41:46,361/:    LOCAL      Deleting file                     - /home/egor-home/Clouds/Yandex.Disk/МАИ/WING IN GROUND EFFECT VEHICLE_ MODELLING AND CONTROL.pdf
Traceback (most recent call last):
  File "/home/egor-home/git/RCloneSync/RCloneSync.py", line 529, in <module>
    status = bidirSync()
  File "/home/egor-home/git/RCloneSync/RCloneSync.py", line 354, in bidirSync
    if rcloneCmd ('delete', src, switches, linenum=inspect.getframeinfo(inspect.currentframe()).lineno): return RTN_CRITICAL
  File "/home/egor-home/git/RCloneSync/RCloneSync.py", line 97, in rcloneCmd
    if not subprocess.call(processArgs):  return 0
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

Also, it would be convenient to have separate option to delete or hint where to find `RCloneSync_LOCK`.

Thanks

**Comment by cjnaz** [comment]
You need to place 1 or more check files within your local file system the
do a firstsync.
